AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  BookingTable:
    Type: AWS::Serverless::SimpleTable
    Properties: {}
  RoomTable:
    Type: AWS::Serverless::SimpleTable
    Properties: {}
  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties: {}
  EventHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: event_handler/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
      - x86_64
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          BOOKING_TABLE: !Ref BookingTable
          ROOM_TABLE: !Ref RoomTable
          USER_TABLE: !Ref UserTable          
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref BookingTable
      - DynamoDBCrudPolicy:
          TableName: !Ref RoomTable
      - DynamoDBCrudPolicy:
          TableName: !Ref UserTable
